### ISSUE TITLE
EULAに同意していなくてもbotの機能が利用できる可能性

### ISSUE THREAD

**Issue by Steve-0628** [p1atdev/tchecker.js#1]
ざっとコードを読んだのですが、すべてのコマンドにユーザーのEULAの同意状態のチェックが挟まれていないように見えます。
検温をする動作など、明らかにEULAへの同意を必要とするものについてはチェックするべきだと思います。

**Comment by p1atdev** [comment]
ごめんなさい

**Comment by p1atdev** [comment]
てかそれマ？

**Comment by Steve-0628** [comment]
脳内コード解釈が間違っていなければマジだと思います

**Comment by p1atdev** [comment]
直しといたよ

**Comment by Steve-0628** [comment]
治ったらしい
